export const questions = [
  {
    statement_one: 'All liquids are wet.',
    statement_two: 'Oil is a liquid.',
    conclusion: 'Oil is wet.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds can fly.',
    statement_two: 'Penguins are birds.',
    conclusion: 'Penguins can fly.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All mammals have fur.',
    statement_two: 'Whales are mammals.',
    conclusion: 'Whales have fur.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All fruits have seeds.',
    statement_two: 'Bananas are fruits.',
    conclusion: 'Bananas have seeds.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All dogs bark.',
    statement_two: 'Labradors are dogs.',
    conclusion: 'Labradors bark.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals conduct electricity.',
    statement_two: 'Copper is a metal.',
    conclusion: 'Copper conducts electricity.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have six legs.',
    statement_two: 'Spiders are insects.',
    conclusion: 'Spiders have six legs.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All flowers bloom in spring.',
    statement_two: 'Roses are flowers.',
    conclusion: 'Roses bloom in spring.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All vehicles have wheels.',
    statement_two: 'Bicycles are vehicles.',
    conclusion: 'Bicycles have wheels.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish live in water.',
    statement_two: 'Sharks are fish.',
    conclusion: 'Sharks live in water.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All humans have hearts.',
    statement_two: 'Doctors are humans.',
    conclusion: 'Doctors have hearts.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All machines need fuel to operate.',
    statement_two: 'Laptops are machines.',
    conclusion: 'Laptops need fuel to operate.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All vegetables are green.',
    statement_two: 'Carrots are vegetables.',
    conclusion: 'Carrots are green.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All snakes are reptiles.',
    statement_two: 'Cobra is a snake.',
    conclusion: 'Cobra is a reptile.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids freeze at 0°C.',
    statement_two: 'Water is a liquid.',
    conclusion: 'Water freezes at 0°C.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fruits are sweet.',
    statement_two: 'Lemons are fruits.',
    conclusion: 'Lemons are sweet.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All animals can move.',
    statement_two: 'Plants are animals.',
    conclusion: 'Plants can move.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All planets orbit the sun.',
    statement_two: 'Earth is a planet.',
    conclusion: 'Earth orbits the sun.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'Chickens are birds.',
    conclusion: 'Chickens lay eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All rocks are hard.',
    statement_two: 'Chalk is a rock.',
    conclusion: 'Chalk is hard.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All humans have brains.',
    statement_two: 'Scientists are humans.',
    conclusion: 'Scientists have brains.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids evaporate.',
    statement_two: 'Mercury is a liquid.',
    conclusion: 'Mercury evaporates.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds have feathers.',
    statement_two: 'Eagles are birds.',
    conclusion: 'Eagles have feathers.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All books are educational.',
    statement_two: 'Comics are books.',
    conclusion: 'Comics are educational.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All reptiles have scales.',
    statement_two: 'Lizards are reptiles.',
    conclusion: 'Lizards have scales.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All planets have moons.',
    statement_two: 'Mars is a planet.',
    conclusion: 'Mars has moons.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All animals breathe air.',
    statement_two: 'Dolphins are animals.',
    conclusion: 'Dolphins breathe air.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All clouds bring rain.',
    statement_two: 'Cumulus is a type of cloud.',
    conclusion: 'Cumulus clouds bring rain.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All trees lose their leaves in autumn.',
    statement_two: 'Pine trees are trees.',
    conclusion: 'Pine trees lose their leaves in autumn.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All cars run on petrol.',
    statement_two: 'Electric cars are cars.',
    conclusion: 'Electric cars run on petrol.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds sing.',
    statement_two: 'Crows are birds.',
    conclusion: 'Crows sing.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All mammals give live birth.',
    statement_two: 'Platypus is a mammal.',
    conclusion: 'Platypus gives live birth.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All humans have teeth.',
    statement_two: 'Babies are humans.',
    conclusion: 'Babies have teeth.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All planets have rings.',
    statement_two: 'Saturn is a planet.',
    conclusion: 'Saturn has rings.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All flowers are colorful.',
    statement_two: 'Lilies are flowers.',
    conclusion: 'Lilies are colorful.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metal objects are magnetic.',
    statement_two: 'Gold is a metal object.',
    conclusion: 'Gold is magnetic.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All diamonds are expensive.',
    statement_two: 'Cubic zirconia is a diamond.',
    conclusion: 'Cubic zirconia is expensive.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All plants need sunlight.',
    statement_two: 'Ferns are plants.',
    conclusion: 'Ferns need sunlight.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have wings.',
    statement_two: 'Ants are insects.',
    conclusion: 'Ants have wings.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All fruits are juicy.',
    statement_two: 'Apples are fruits.',
    conclusion: 'Apples are juicy.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All cats purr.',
    statement_two: 'Tigers are cats.',
    conclusion: 'Tigers purr.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds migrate.',
    statement_two: 'Owls are birds.',
    conclusion: 'Owls migrate.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All stones sink in water.',
    statement_two: 'Pumice is a stone.',
    conclusion: 'Pumice sinks in water.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All reptiles lay eggs.',
    statement_two: 'Snakes are reptiles.',
    conclusion: 'Snakes lay eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have lungs.',
    statement_two: 'Bats are mammals.',
    conclusion: 'Bats have lungs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All plants need water.',
    statement_two: 'Cacti are plants.',
    conclusion: 'Cacti need water.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are shiny.',
    statement_two: 'Aluminum is a metal.',
    conclusion: 'Aluminum is shiny.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds eat insects.',
    statement_two: 'Flamingos are birds.',
    conclusion: 'Flamingos eat insects.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All humans have hair.',
    statement_two: 'Babies are humans.',
    conclusion: 'Babies have hair.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish have scales.',
    statement_two: 'Salmon are fish.',
    conclusion: 'Salmon have scales.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All vegetables are roots.',
    statement_two: 'Potatoes are vegetables.',
    conclusion: 'Potatoes are roots.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All dogs are friendly.',
    statement_two: 'Rottweilers are dogs.',
    conclusion: 'Rottweilers are friendly.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All humans are omnivores.',
    statement_two: 'Vegans are humans.',
    conclusion: 'Vegans are omnivores.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All cars are fast.',
    statement_two: 'Ferraris are cars.',
    conclusion: 'Ferraris are fast.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All planets have atmospheres.',
    statement_two: 'Venus is a planet.',
    conclusion: 'Venus has an atmosphere.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids are drinkable.',
    statement_two: 'Juice is a liquid.',
    conclusion: 'Juice is drinkable.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fruits are red.',
    statement_two: 'Apples are fruits.',
    conclusion: 'Apples are red.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All books are fiction.',
    statement_two: 'Biographies are books.',
    conclusion: 'Biographies are fiction.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All computers are fast.',
    statement_two: 'Supercomputers are computers.',
    conclusion: 'Supercomputers are fast.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds eat seeds.',
    statement_two: 'Eagles are birds.',
    conclusion: 'Eagles eat seeds.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All humans walk upright.',
    statement_two: 'Athletes are humans.',
    conclusion: 'Athletes walk upright.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All reptiles are cold-blooded.',
    statement_two: 'Snakes are reptiles.',
    conclusion: 'Snakes are cold-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are conductors.',
    statement_two: 'Iron is a metal.',
    conclusion: 'Iron is a conductor.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All stones are heavy.',
    statement_two: 'Pebbles are stones.',
    conclusion: 'Pebbles are heavy.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All dogs are mammals.',
    statement_two: 'Poodles are dogs.',
    conclusion: 'Poodles are mammals.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All humans are mammals.',
    statement_two: 'Babies are humans.',
    conclusion: 'Babies are mammals.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids are transparent.',
    statement_two: 'Milk is a liquid.',
    conclusion: 'Milk is transparent.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All animals eat plants.',
    statement_two: 'Cows are animals.',
    conclusion: 'Cows eat plants.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds are predators.',
    statement_two: 'Pigeons are birds.',
    conclusion: 'Pigeons are predators.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All metals are strong.',
    statement_two: 'Iron is a metal.',
    conclusion: 'Iron is strong.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All animals have legs.',
    statement_two: 'Snakes are animals.',
    conclusion: 'Snakes have legs.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds can swim.',
    statement_two: 'Penguins are birds.',
    conclusion: 'Penguins can swim.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All trees have leaves.',
    statement_two: 'Maples are trees.',
    conclusion: 'Maples have leaves.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids can be frozen.',
    statement_two: 'Water is a liquid.',
    conclusion: 'Water can be frozen.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All stones are hard.',
    statement_two: 'Granite is a stone.',
    conclusion: 'Granite is hard.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All vegetables are roots.',
    statement_two: 'Carrots are vegetables.',
    conclusion: 'Carrots are roots.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have beaks.',
    statement_two: 'Owls are birds.',
    conclusion: 'Owls have beaks.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals produce milk.',
    statement_two: 'Whales are mammals.',
    conclusion: 'Whales produce milk.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish have gills.',
    statement_two: 'Salmon are fish.',
    conclusion: 'Salmon have gills.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals rust.',
    statement_two: 'Stainless steel is a metal.',
    conclusion: 'Stainless steel rusts.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds can fly.',
    statement_two: 'Ostriches are birds.',
    conclusion: 'Ostriches can fly.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'Penguins are birds.',
    conclusion: 'Penguins lay eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All vegetables grow underground.',
    statement_two: 'Onions are vegetables.',
    conclusion: 'Onions grow underground.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have feathers.',
    statement_two: 'Chickens are birds.',
    conclusion: 'Chickens have feathers.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are shiny.',
    statement_two: 'Steel is a metal.',
    conclusion: 'Steel is shiny.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids are drinkable.',
    statement_two: 'Oil is a liquid.',
    conclusion: 'Oil is drinkable.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All dogs are loyal.',
    statement_two: 'Beagles are dogs.',
    conclusion: 'Beagles are loyal.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds can swim.',
    statement_two: 'Ducks are birds.',
    conclusion: 'Ducks can swim.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are heavy.',
    statement_two: 'Aluminum is a metal.',
    conclusion: 'Aluminum is heavy.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All trees are green.',
    statement_two: 'Oak trees are trees.',
    conclusion: 'Oak trees are green.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds have wings.',
    statement_two: 'Sparrows are birds.',
    conclusion: 'Sparrows have wings.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals lay eggs.',
    statement_two: 'Platypuses are mammals.',
    conclusion: 'Platypuses lay eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All snakes are venomous.',
    statement_two: 'Garter snakes are snakes.',
    conclusion: 'Garter snakes are venomous.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All machines require electricity.',
    statement_two: 'Telephones are machines.',
    conclusion: 'Telephones require electricity.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids are cold.',
    statement_two: 'Milk is a liquid.',
    conclusion: 'Milk is cold.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds have beaks.',
    statement_two: 'Parrots are birds.',
    conclusion: 'Parrots have beaks.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have tails.',
    statement_two: 'Humans are mammals.',
    conclusion: 'Humans have tails.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All books are on shelves.',
    statement_two: 'Novels are books.',
    conclusion: 'Novels are on shelves.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All reptiles lay eggs.',
    statement_two: 'Turtles are reptiles.',
    conclusion: 'Turtles lay eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All plants grow in soil.',
    statement_two: 'Cacti are plants.',
    conclusion: 'Cacti grow in soil.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All metals are heavy.',
    statement_two: 'Gold is a metal.',
    conclusion: 'Gold is heavy.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All cars are red.',
    statement_two: 'Ferraris are cars.',
    conclusion: 'Ferraris are red.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All computers need electricity.',
    statement_two: 'Laptops are computers.',
    conclusion: 'Laptops need electricity.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All animals can talk.',
    statement_two: 'Cats are animals.',
    conclusion: 'Cats can talk.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All fish can fly.',
    statement_two: 'Flying fish are fish.',
    conclusion: 'Flying fish can fly.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All vegetables are fruits.',
    statement_two: 'Tomatoes are vegetables.',
    conclusion: 'Tomatoes are fruits.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All fruits are fresh',
    statement_two: 'An apple is a fruit.',
    conclusion: 'An apple per day, take doctor away.',
    is_conclusion_correct: true,
  },
];
