export const questions = [
  {
    statement_one: 'All humans are mortal.',
    statement_two: 'Socrates is a human.',
    conclusion: 'Socrates is mortal.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds can fly.',
    statement_two: 'Penguins are birds.',
    conclusion: 'Penguins can fly.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All planets have gravity.',
    statement_two: 'Mars is a planet.',
    conclusion: 'Mars has gravity.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All snakes are reptiles.',
    statement_two: 'A cobra is a snake.',
    conclusion: 'A cobra is a reptile.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have backbones.',
    statement_two: 'A dolphin is a mammal.',
    conclusion: 'A dolphin has a backbone.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds are warm-blooded.',
    statement_two: 'A sparrow is a bird.',
    conclusion: 'A sparrow is warm-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are shiny.',
    statement_two: 'Aluminum is a metal.',
    conclusion: 'Aluminum is shiny.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fruits contain seeds.',
    statement_two: 'An apple is a fruit.',
    conclusion: 'An apple contains seeds.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have six legs.',
    statement_two: 'A beetle is an insect.',
    conclusion: 'A beetle has six legs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All flowers bloom.',
    statement_two: 'A tulip is a flower.',
    conclusion: 'A tulip blooms.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'A swan is a bird.',
    conclusion: 'A swan lays eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish have fins.',
    statement_two: 'A trout is a fish.',
    conclusion: 'A trout has fins.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have fur.',
    statement_two: 'A lion is a mammal.',
    conclusion: 'A lion has fur.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have beaks.',
    statement_two: 'A duck is a bird.',
    conclusion: 'A duck has a beak.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals are warm-blooded.',
    statement_two: 'A bat is a mammal.',
    conclusion: 'A bat is warm-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have feathers.',
    statement_two: 'A parrot is a bird.',
    conclusion: 'A parrot has feathers.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All snakes are cold-blooded.',
    statement_two: 'A viper is a snake.',
    conclusion: 'A viper is cold-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish swim.',
    statement_two: 'A goldfish is a fish.',
    conclusion: 'A goldfish swims.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All cats are mammals.',
    statement_two: 'A tiger is a cat.',
    conclusion: 'A tiger is a mammal.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All cars are vehicles.',
    statement_two: 'A bicycle is a vehicle.',
    conclusion: 'A bicycle is a car.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'Some fruits are sweet.',
    statement_two: 'An apple is a fruit.',
    conclusion: 'An apple is sweet.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All dogs are animals.',
    statement_two: 'A wolf is a dog.',
    conclusion: 'A wolf is an animal.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All flowers are plants.',
    statement_two: 'A rose is a flower.',
    conclusion: 'A rose is a plant.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish live in water.',
    statement_two: 'A shark is a fish.',
    conclusion: 'A shark lives in water.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals conduct electricity.',
    statement_two: 'Iron is a metal.',
    conclusion: 'Iron conducts electricity.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All students study.',
    statement_two: 'John is a student.',
    conclusion: 'John studies.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All teachers teach.',
    statement_two: 'Mr. Smith is a teacher.',
    conclusion: 'Mr. Smith teaches.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All rectangles have four sides.',
    statement_two: 'A square is a rectangle.',
    conclusion: 'A square has four sides.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All laptops are computers.',
    statement_two: 'A MacBook is a laptop.',
    conclusion: 'A MacBook is a computer.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids flow.',
    statement_two: 'Water is a liquid.',
    conclusion: 'Water flows.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have fur.',
    statement_two: 'A whale is a mammal.',
    conclusion: 'A whale has fur.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All squares have four equal sides.',
    statement_two: 'A rhombus is a square.',
    conclusion: 'A rhombus has four equal sides.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All liquids are wet.',
    statement_two: 'Oil is a liquid.',
    conclusion: 'Oil is wet.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All dogs bark.',
    statement_two: 'A golden retriever is a dog.',
    conclusion: 'A golden retriever barks.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have six legs.',
    statement_two: 'A spider is an insect.',
    conclusion: 'A spider has six legs.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All reptiles are cold-blooded.',
    statement_two: 'A snake is a reptile.',
    conclusion: 'A snake is cold-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have feathers.',
    statement_two: 'An ostrich is a bird.',
    conclusion: 'An ostrich has feathers.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fruits have seeds.',
    statement_two: 'A banana is a fruit.',
    conclusion: 'A banana has seeds.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All vegetables are healthy.',
    statement_two: 'Broccoli is a vegetable.',
    conclusion: 'Broccoli is healthy.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals give live birth.',
    statement_two: 'A platypus is a mammal.',
    conclusion: 'A platypus gives live birth.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'A robin is a bird.',
    conclusion: 'A robin lays eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All stars are hot.',
    statement_two: 'The Sun is a star.',
    conclusion: 'The Sun is hot.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All planets orbit the sun.',
    statement_two: 'Earth is a planet.',
    conclusion: 'Earth orbits the sun.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are shiny.',
    statement_two: 'Copper is a metal.',
    conclusion: 'Copper is shiny.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All numbers are even or odd.',
    statement_two: '7 is a number.',
    conclusion: '7 is odd.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All triangles have three sides.',
    statement_two: 'A scalene triangle is a triangle.',
    conclusion: 'A scalene triangle has three sides.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All paintings are art.',
    statement_two: 'The Mona Lisa is a painting.',
    conclusion: 'The Mona Lisa is art.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All books have pages.',
    statement_two: 'A dictionary is a book.',
    conclusion: 'A dictionary has pages.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All apples are fruits.',
    statement_two: 'A Granny Smith is an apple.',
    conclusion: 'A Granny Smith is a fruit.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All shoes have laces.',
    statement_two: 'Sneakers are shoes.',
    conclusion: 'Sneakers have laces.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All laptops have keyboards.',
    statement_two: 'A Chromebook is a laptop.',
    conclusion: 'A Chromebook has a keyboard.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All rivers flow into the ocean.',
    statement_two: 'The Nile is a river.',
    conclusion: 'The Nile flows into the ocean.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds can sing.',
    statement_two: 'A canary is a bird.',
    conclusion: 'A canary can sing.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have backbones.',
    statement_two: 'A dolphin is a mammal.',
    conclusion: 'A dolphin has a backbone.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All computers can process data.',
    statement_two: 'A server is a computer.',
    conclusion: 'A server can process data.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All cars have engines.',
    statement_two: 'A Tesla is a car.',
    conclusion: 'A Tesla has an engine.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All triangles have angles.',
    statement_two: 'A right triangle is a triangle.',
    conclusion: 'A right triangle has angles.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All snakes are reptiles.',
    statement_two: 'A python is a snake.',
    conclusion: 'A python is a reptile.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All liquids have volume.',
    statement_two: 'Mercury is a liquid.',
    conclusion: 'Mercury has volume.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All books are written.',
    statement_two: 'A novel is a book.',
    conclusion: 'A novel is written.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All ships float.',
    statement_two: 'The Titanic was a ship.',
    conclusion: 'The Titanic floated.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All squares are rectangles.',
    statement_two: 'A square is a shape.',
    conclusion: 'A square is a rectangle.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All planets are round.',
    statement_two: 'Mars is a planet.',
    conclusion: 'Mars is round.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have beaks.',
    statement_two: 'A parrot is a bird.',
    conclusion: 'A parrot has a beak.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All vegetables grow in soil.',
    statement_two: 'Carrots are vegetables.',
    conclusion: 'Carrots grow in soil.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All plants need sunlight.',
    statement_two: 'A cactus is a plant.',
    conclusion: 'A cactus needs sunlight.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All wheels are round.',
    statement_two: 'A car tire is a wheel.',
    conclusion: 'A car tire is round.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All clocks tell time.',
    statement_two: 'A digital clock is a clock.',
    conclusion: 'A digital clock tells time.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have wings.',
    statement_two: 'A penguin is a bird.',
    conclusion: 'A penguin has wings.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds fly.',
    statement_two: 'An ostrich is a bird.',
    conclusion: 'An ostrich flies.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All plants produce oxygen.',
    statement_two: 'A tree is a plant.',
    conclusion: 'A tree produces oxygen.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals drink milk as infants.',
    statement_two: 'A baby whale is a mammal.',
    conclusion: 'A baby whale drinks milk.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All flowers bloom in spring.',
    statement_two: 'A daffodil is a flower.',
    conclusion: 'A daffodil blooms in spring.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds build nests.',
    statement_two: 'An eagle is a bird.',
    conclusion: 'An eagle builds a nest.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish swim.',
    statement_two: 'A salmon is a fish.',
    conclusion: 'A salmon swims.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals have lungs.',
    statement_two: 'A whale is a mammal.',
    conclusion: 'A whale has lungs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All triangles have angles.',
    statement_two: 'An equilateral triangle is a triangle.',
    conclusion: 'An equilateral triangle has angles.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have wings.',
    statement_two: 'A butterfly is an insect.',
    conclusion: 'A butterfly has wings.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All squares have equal sides.',
    statement_two: 'A rectangle is a square.',
    conclusion: 'A rectangle has equal sides.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'A penguin is a bird.',
    conclusion: 'A penguin lays eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All metals are magnetic.',
    statement_two: 'Gold is a metal.',
    conclusion: 'Gold is magnetic.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All reptiles lay eggs.',
    statement_two: 'A turtle is a reptile.',
    conclusion: 'A turtle lays eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have feathers.',
    statement_two: 'A parrot is a bird.',
    conclusion: 'A parrot has feathers.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have antennas.',
    statement_two: 'A beetle is an insect.',
    conclusion: 'A beetle has antennas.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All flowers are colorful.',
    statement_two: 'A sunflower is a flower.',
    conclusion: 'A sunflower is colorful.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds can fly.',
    statement_two: 'An ostrich is a bird.',
    conclusion: 'An ostrich can fly.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds have beaks.',
    statement_two: 'A sparrow is a bird.',
    conclusion: 'A sparrow has a beak.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fruits have seeds.',
    statement_two: 'A watermelon is a fruit.',
    conclusion: 'A watermelon has seeds.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds build nests.',
    statement_two: 'A robin is a bird.',
    conclusion: 'A robin builds a nest.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All dogs have tails.',
    statement_two: 'A beagle is a dog.',
    conclusion: 'A beagle has a tail.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have six legs.',
    statement_two: 'An ant is an insect.',
    conclusion: 'An ant has six legs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish have scales.',
    statement_two: 'A trout is a fish.',
    conclusion: 'A trout has scales.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'A sparrow is a bird.',
    conclusion: 'A sparrow lays eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All mammals are warm-blooded.',
    statement_two: 'A bear is a mammal.',
    conclusion: 'A bear is warm-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All reptiles are cold-blooded.',
    statement_two: 'A lizard is a reptile.',
    conclusion: 'A lizard is cold-blooded.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All flowers have petals.',
    statement_two: 'A rose is a flower.',
    conclusion: 'A rose has petals.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds can fly.',
    statement_two: 'An ostrich is a bird.',
    conclusion: 'An ostrich can fly.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All fruits are sweet.',
    statement_two: 'A lemon is a fruit.',
    conclusion: 'A lemon is sweet.',
    is_conclusion_correct: false,
  },
  {
    statement_one: 'All birds have feathers.',
    statement_two: 'A penguin is a bird.',
    conclusion: 'A penguin has feathers.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have wings.',
    statement_two: 'A grasshopper is an insect.',
    conclusion: 'A grasshopper has wings.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All snakes are dangerous.',
    statement_two: 'A cobra is a snake.',
    conclusion: 'A cobra is dangerous.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds lay eggs.',
    statement_two: 'A chicken is a bird.',
    conclusion: 'A chicken lays eggs.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All birds have wings.',
    statement_two: 'A duck is a bird.',
    conclusion: 'A duck has wings.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All trees have leaves.',
    statement_two: 'A pine tree is a tree.',
    conclusion: 'A pine tree has leaves.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All fish have gills.',
    statement_two: 'A goldfish is a fish.',
    conclusion: 'A goldfish has gills.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All insects have antennas.',
    statement_two: 'A moth is an insect.',
    conclusion: 'A moth has antennas.',
    is_conclusion_correct: true,
  },
  {
    statement_one: 'All reptiles lay eggs.',
    statement_two: 'A crocodile is a reptile.',
    conclusion: 'A crocodile lays eggs.',
    is_conclusion_correct: true,
  },
];
